version: "3.8"
services:
  person-app:
    build: .
    container_name: person-app
    ports:
      - target: 8081
        published: 8081
    depends_on:
      - redis
      - person-db
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://person-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  person-db:
    image: postgres
    container_name: person-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    container_name: redis